name = "cloudflare-auth-worker"
main = "index.ts"
compatibility_date = "2024-01-01"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "test"
database_id = "b3ad23cf-64b2-488b-9371-0cd4bd398156" # اترك هذا كما هو وعدّله لاحقاً

# Worker configuration
[vars]
ENVIRONMENT = "production"

# Development settings
[env.development]
[env.development.vars]
ENVIRONMENT = "development"





